FORMAT: 1A
HOST: https://dsblabs.herokuapp.com

# DSB Stationsafgange
RESTful gateway for DSB Labs Stationsafgange.

## Stations [/stations]
### List all Stations [GET]
+ Response 200 (application/json)

        [
            {
                abbreviation: "ALB",
                name: "Albertslund",
                uic: "8600621",
                country_code: "86",
                country_name: "DK",
                queue: "https://dsblabs.herokuapp.com/queue?uic=8600621"
            }
        ]

## Queue [/queue{?uic}]
A single station queue with all its details.

+ Parameters
    + uic (required, number, `8600621`) ... Numeric `id` of the Station to perform action with. Has example value.

### Retrieve a station queue [GET]
+ Response 200 (application/json)

    + Body

            [
                {
                    id: "6c26cd47-778b-44dd-9cd8-33f616f5cfd7",
                    station_uic: "8600621",
                    train_type: "S-tog",
                    destination_name: "Holte",
                    destination_id: "8600677",
                    track: "3",
                    generated: "2017-04-26T12:29:00+00:00",
                    train_number: "23138",
                    destination_country_code: "86",
                    scheduled_arrival: null,
                    scheduled_departure: null,
                    arrival_delay: null,
                    departure_delay: null,
                    cancelled: false,
                    line: "B",
                    direction: "Nord",
                    minutes_to_departure: "6"
                }
            ]